image: $DOCKER_IMAGE

before_script:
  # install ssh-agent
  - 'which ssh-agent || ( $SSH_AGENT_INSTALL )'
  # run ssh-agent
  - eval $(ssh-agent -s)
  # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

stages:
  - release

release:
  stage: release
  tags:
    - docker
  script:
    - ls -la
    - git status
    - source ./release.sh
    - doRelease
  only:
    - $RELEASE_TRIGGER_BRANCH
