image: $DOCKER_IMAGE

before_script:
    - export PREPARE_RELEASE_SH_CHMOD=`stat --format '%a' ./prepare-release.sh`
    - chmod u+x prepare-release.sh
    - . ./prepare-release.sh

release:
    script:
        - ls -la
        - git status
        - mvn -DdevelopmentVersion=$DEV_VERSION -DreleaseVersion=$RELEASE_VERSION -Dmessage="[maven-release-plugin] [ci skip] Updating parent version" release:clean versions:update-parent scm:checkin release:prepare release:perform $MAVEN_RELEASE_ADDITIONAL_ARGS
    only:
        - $RELEASE_TRIGGER_BRANCH
