image: $DOCKER_IMAGE

before_script:
  # check git exists
  - 'which git || ( echo "git executable is not found in $DOCKER_IMAGE\nUse a Docker image with prerequisites installed" )'
  # check ssh-agent exists
  - 'which ssh-agent || ( echo "ssh-agent executable is not found in $DOCKER_IMAGE\nUse a Docker image with prerequisites installed" )'
  # run ssh-agent
  - eval $(ssh-agent -s)
  # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

stages:
  - release

release:
  stage: release
  tags:
    - docker
  script:
    - ls -la
    - git status
    - source ./release.sh
    - doRelease
  only:
    - $RELEASE_TRIGGER_BRANCH
