image: debovema/docker-mvn

before_script:
    - export RELEASE_SH_CHMOD=`stat --format '%a' ./prepareRelease.sh`
    - chmod u+x prepareRelease.sh
    - . ./prepareRelease.sh

release:
    script:
        - mvn -DdevelopmentVersion=$DEV_VERSION -DreleaseVersion=$RELEASE_VERSION -Dmessage="[maven-release-plugin] [ci skip] Updating parent version" release:clean versions:update-parent scm:checkin release:prepare release:perform $MAVEN_RELEASE_ADDITIONAL_ARGS
    only:
        - $RELEASE_TRIGGER_BRANCH
