image: $DOCKER_IMAGE

release:
    stage:
        - release
    tags:
        - docker
    script:
        - ls -la
        - git status
        - source ./release.sh
        - executeRelease
        - mvn -DdevelopmentVersion=$DEV_VERSION -DreleaseVersion=$RELEASE_VERSION -Dmessage="[maven-release-plugin] [ci skip] Updating parent version" release:clean versions:update-parent scm:checkin release:prepare release:perform $MAVEN_RELEASE_ADDITIONAL_ARGS
    only:
        - $RELEASE_TRIGGER_BRANCH
